import type { Metadata } from "next";
import { Inter, Allan } from "next/font/google";
import "./globals.css";

const allan = Allan({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-allan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${allan.variable} font-sans`}>{children}</body>
    </html>
  );
}
