import type { Metadata } from "next";
import { Inter, Allan, Montserrat, PT_Serif } from "next/font/google";
import "./globals.css";

import AuthProvider from "./SessionProvider";
import ThemeProviderWrapper from "./ThemeProvider";
import NavBar from "./components/NavBar/NavBar";
const ptSerif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ptserif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSerif.variable} font-sans container`}>
        <ThemeProviderWrapper>
          <AuthProvider>
            <NavBar />
            {children}
          </AuthProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
